on:
  push:
    branches:
    - main
    
permissions: write-all
    
jobs:
  ADD_COPYRIGHT_HEADER:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix
          
      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
          remove: './.github/workflows/**'
